-- Create bio_data table for student bio-data information
CREATE TABLE IF NOT EXISTS `bio_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  `student_id` int NOT NULL,
  
  -- Personal Details
  `surname` varchar(100) DEFAULT NULL,
  `other_names` varchar(200) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `sex` enum('MALE','FEMALE') DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `religion` varchar(100) DEFAULT NULL,
  `district` varchar(100) DEFAULT NULL,
  `nationality` varchar(100) DEFAULT 'UGANDAN',
  `national_id` varchar(50) DEFAULT NULL,
  `passport_number` varchar(50) DEFAULT NULL,
  `marital_status` enum('SINGLE','MARRIED','DIVORCED','WIDOWED') DEFAULT 'SINGLE',
  `address` text DEFAULT NULL,
  
  -- Guardian Details
  `guardian_full_name` varchar(255) DEFAULT NULL,
  `guardian_relationship` varchar(100) DEFAULT NULL,
  `guardian_email` varchar(255) DEFAULT NULL,
  `guardian_phone` varchar(20) DEFAULT NULL,
  `guardian_address` text DEFAULT NULL,
  `guardian_occupation` varchar(100) DEFAULT NULL,
  
  -- Next of Kin Details
  `next_of_kin_name` varchar(255) DEFAULT NULL,
  `next_of_kin_relationship` varchar(100) DEFAULT NULL,
  `next_of_kin_phone` varchar(20) DEFAULT NULL,
  `next_of_kin_email` varchar(255) DEFAULT NULL,
  `next_of_kin_address` text DEFAULT NULL,
  `next_of_kin_occupation` varchar(100) DEFAULT NULL,
  
  -- Academic Details
  `registration_number` varchar(50) DEFAULT NULL,
  `academic_status` varchar(100) DEFAULT 'NORMAL PROGRESS',
  `billing_category` varchar(100) DEFAULT 'UGANDAN',
  `campus` varchar(100) DEFAULT 'MAIN CAMPUS',
  `programme_version` varchar(20) DEFAULT NULL,
  `residence_status` enum('RESIDENT','NON-RESIDENT') DEFAULT 'RESIDENT',
  `intake` varchar(50) DEFAULT NULL,
  `hall_of_attachment` varchar(100) DEFAULT NULL,
  `entry_academic_year` varchar(20) DEFAULT NULL,
  `hall_of_residence` varchar(100) DEFAULT NULL,
  `entry_study_year` varchar(20) DEFAULT NULL,
  `fees_waiver` varchar(100) DEFAULT NULL,
  `current_study_year` varchar(20) DEFAULT NULL,
  `has_completed` enum('YES','NO') DEFAULT 'NO',
  `study_type` enum('DAY','EVENING','WEEKEND') DEFAULT 'DAY',
  `on_loan_scheme` enum('YES','NO') DEFAULT 'NO',
  `sponsorship` varchar(100) DEFAULT 'GOVERNMENT',
  `affiliated` enum('YES','NO') DEFAULT 'NO',
  
  -- Metadata
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_student_bio_data` (`student_id`),
  KEY `idx_bio_data_student` (`student_id`),
  KEY `idx_bio_data_national_id` (`national_id`),
  KEY `idx_bio_data_passport` (`passport_number`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Insert sample bio-data for existing student
INSERT INTO `bio_data` (
  `student_id`,
  `surname`,
  `other_names`,
  `email`,
  `phone`,
  `sex`,
  `date_of_birth`,
  `religion`,
  `district`,
  `nationality`,
  `national_id`,
  `passport_number`,
  `marital_status`,
  `address`,
  `guardian_full_name`,
  `guardian_relationship`,
  `guardian_email`,
  `guardian_phone`,
  `guardian_address`,
  `guardian_occupation`,
  `next_of_kin_name`,
  `next_of_kin_relationship`,
  `next_of_kin_phone`,
  `next_of_kin_email`,
  `next_of_kin_address`,
  `next_of_kin_occupation`,
  `registration_number`,
  `academic_status`,
  `billing_category`,
  `campus`,
  `programme_version`,
  `residence_status`,
  `intake`,
  `hall_of_attachment`,
  `entry_academic_year`,
  `hall_of_residence`,
  `entry_study_year`,
  `fees_waiver`,
  `current_study_year`,
  `has_completed`,
  `study_type`,
  `on_loan_scheme`,
  `sponsorship`,
  `affiliated`
) VALUES (
  1, -- student_id for John Doe
  'Doe',
  'John',
  'john.doe@student.eyecab.edu',
  '+256701234567',
  'MALE',
  '2003-03-18',
  'CHRISTIAN',
  'KAMPALA',
  'UGANDAN',
  'CM12345678901234',
  NULL,
  'SINGLE',
  'Plot 123, Kampala Road, Kampala, Uganda',
  'APIO SARAH',
  'MOTHER',
  'apio.sarah@gmail.com',
  '0773076597',
  'Plot 456, Jinja Road, Kampala, Uganda',
  'TEACHER',
  NULL, -- No next of kin record as mentioned in the original modal
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '24/U/2185',
  'NORMAL PROGRESS',
  'UGANDAN',
  'MAIN CAMPUS',
  'V2022',
  'RESIDENT',
  'AUGUST',
  'MITCHELL',
  '2024/2025',
  'MITCHELL',
  'YEAR 1',
  'GOVT',
  'YEAR 3',
  'NO',
  'DAY',
  'NO',
  'GOVERNMENT',
  'NO'
);